Hessam Hashemizade - 9535503

HW5 - Computational Intelligence

# Defining the membership functions

As the first step to this project, we must define the membership functions associated with each of the variables x, \phi, and \theta. Since each of the areas corresponding to different fuzzy areas can be presented using the triangel membershi function, we make greate use of its definition in our code. 

Here you can see paramethers for each of the fuzzy areas, extracted from the problem statement. 

This step is the first step for the Truck Backer-Upper Problem.

In [ ]:
# Membership Functions - PHI X THETA - Phase 1

def triangle_mem(data,pack):
    (a, m, b,down_co, up_co, stable) = pack
    if stable is not None:
        if stable[0] <= data and data <= stable[1]:
            return stable[2]
    if down_co is not None and data < down_co:
        return 0
    if up_co is not None and up_co < data:
        return 0
    
    if data < a:
        return 0
    if a <= data and data < m:
        return ((data - a )/(m - a))
    if m <= data and data < b:
        return ((b - data )/(b - m))
    if b <= data:
        return 0
    
    

phi = {
    "S3":(-115,-65,-15,-90,None,None),
    "S2":(-45,0,45,None,None,None),
    "S1":(-45,0,45,None,None,None),
    "CE":(15,52.5,90,None,None,None),
    "B1":(80,90,100,None,None,None),
    "B2":(90,127.5,165,None,None,None),
    "B3":(195,245,295,None,270,None)
}

x = {
    "S2":(-4,1.5,7,1.5,None,(0,1.5,1)),
    "S1":(4,7,10,None,None,None),
    "CE":(9,10,11,None,None,None),
    "B1":(10,13,16,None,None,None),
    "B2":(13,18.5,24,None,18.5,(18.5,20,1))
}

theta ={
    "S3":(-60,-40,-20,-40,None,None),
    "S2":(-33,-20,-7,None,None,None),
    "S1":(-14,-7,0,None,None,None),
    "CE":(-4,0,-4,None,None,None),
    "B1":(0,7,14,None,None,None),
    "B2":(7,20,33,None,None,None),
    "B3":(20,40,60,None,40,None)
}

Next code segment presents the datesets stated in the problem statement, set of fourteen sequences starting from an arbitrary point ending approximately at (10,90).

In [ ]:
# Datasets
datasets = []
datasets.append([
                (1, 0, -19),
                (1.95, 9.37, -17.95),
                (2.88, 18.23, -16.90),
                (3.79, 26.59, -15.85),
                (14.65, 34.44, -14.80),
                (5.45, 41.78, -13.75),
                (6.18, 48.60, -12.70),
                (7.48, 54.91, -11.65),
                (7.99, 60.71, -10.60),
                (8.72, 65.99, -9.55),
                (9.01, 70.75, -8.50),
                (9.28, 74.98, -7.45),
                (9.46, 78.70, -6.40),
                (9.59, 81.90, -5.34),
                (9.72, 84.57, -4.30),
                (9.81, 86.72, -3.25),
                (9.88, 88.34, -2.20),
                (9.91, 89.44, 0)
])
datasets.append([
                (1, 90, 18),
                (1.15, 81.11, 16),
                (1.43, 73.19, 14),
                (1.83, 66.24, 12),
                (2.31, 60.27, 10),
                (2.88, 55.29, 8),
                (3.50, 51.30, 6),
                (4.16, 48.31, 4),
                (4.86, 46.31, 2),
                (5.56, 45.31, 0),
                (6.26, 45.31, -2),
                (6.95, 46.31, -4),
                (7.61, 48.31, -6),
                (8.23, 51.30, -8),
                (8.79, 55.29, -10),
                (9.28, 60.27, -12),
                (9.67, 66.24, -14),
                (9.95, 73.19, -16),
                (10.09, 81.11, -18),
                (10.09, 90, 0)
])
datasets.append([
                (1, -90, -30),
                (1.22, -75.52, -29),
                (1.64, -51.49, -28),
                (2.24, -47.92, -27),
                (2.98, -34.80, -26),
                (3.82, -22.13, -25),
                (4.72, -9.93, -24),
                (5.64, 1.80, -23),
                (6.54, 13.06, -22),
                (7.39, 23.86, -21),
                (8.17, 34.18, -20),
                (8.85, 44.04, -19),
                (9.42, 53.40, -18),
                (9.66, 62.29, -17),
                (9.82, 70.69, -16),
                (10.08, 78.62, -15),
                (10.11, 85.05, -14),
                (10.13, 90.02, 0),
])
datasets.append([
            (7,0,-40),
            (7.76,18.75,-38.5),
            (8.51,36.88,-37),
            (9.15,54.40,-35.5),
            (9.62,71.28,-34),
            (9.88,87.51,-3),
            (9.93,89.9,0)
])
datasets.append([
                (7, 90, 12),
                (7.10, 84.03, 10.06),
                (7.29, 79.02, 8.12),
                (7.55, 74.97, 6.18),
                (7.86, 71.89, 4.24),
                (8.21, 69.77, 2.30),
                (8.57, 68.62, 0.34),
                (8.84, 68.44, -1.58),
                (9.19, 69.23, -3.52),
                (9.42, 70.99, -5.46),
                (9.69, 73.72, -7.40),
                (9.81, 77.45, -9.34),
                (10.05, 83.16, -11.28),
                (10.15, 89.67, 0)
])
datasets.append([
                (7, 180, 40),
                (6.23, 161.25, 36.80),
                (5.48, 143.82, 33.60),
                (4.80, 127.76, 30.40),
                (4.27, 113.10, 27.20),
                (3.93, 99.89, 24),
                (3.77, 88.16, 20.80),
                (3.80, 77.93, 17.60),
                (4, 69.23, 14.40),
                (4.35, 62.09, 11.20),
                (4.81, 56.52, 8),
                (5.35, 52.53, 4.80),
                (5.96, 50.12, 1.60),
                (6.60, 49.32, -1.60),
                (7.25, 50.13, -4.80),
                (7.89, 52.53, -11.20),
                (8.49, 56.52, -14.40),
                (9.04, 62.09, -17.60),
                (9.82, 69.23, -20.80),
                (10.02, 78.12, -24),
                (10.05, 89.15, 0)
])
datasets.append([
                (7, -90, -40),
                (7.25, -71.25, -39),
                (7.73, -52.91, -38),
                (8.38, -34.98, -37),
                (9.15, -17.47, -36),
                (9.97, -0.38, -35),
                (10.77, 16.29, -34),
                (11.48, 32.53, -33),
                (12.04, 48.33, -32),
                (12.42, 63.70, -31),
                (12.59, 78.62, -30),
                (12.54, 93.10, -29),
                (12.28, 107.12, -28),
                (11.77, 120.70, 0),
                (11.28, 120.70, 15),
                (10.90, 113.27, 13),
                (10.62, 106.81, 11),
                (10.32, 101.33, 9),
                (10.20, 96.84, 7),
                (10.14, 93.35, 5),
                (10.09, 90.35, 0)
])
datasets.append([
                (13, 0, -40),
                (13.77, 18.75, -36.80),
                (14.52, 36.18, -33.60),
                (15.20, 52.24, -30.40),
                (15.73, 66.90, -27.20),
                (16.08, 80.11, -24),
                (16.23, 91.84, -20.80),
                (16.20, 102.07, -17.60),
                (16, 110.77, -14.4),
                (15.66, 117.91, -11.2),
                (15.20, 123.48, -8),
                (14.66, 127.47,4.8),
                (14.05, 129.87, -1.60),
                (13.41, 130.67, 1.60),
                (12.76, 129.87, 4.80),
                (12.12, 127.47, 8),
                (11.52, 123.48, 11.20),
                (10.98, 117.91, 14.40),
                (10.53, 110.77, 17.60),
                (10.19, 101.07, 20.8),
                (9.99, 90.84, 0)
])
datasets.append([
                (13, 90, -12),
                (12.9, 95.97, -10.05),
                (12.71, 100.97, -8.1),
                (12.45, 105.01, -6.15),
                (12.15, 108.08, -4.20),
                (11.8, 110.18,-2.25),
                (11.44, 111.31,-0.3),
                (11.08,111.46, 1.65),
                (10.72, 110.63, 3.60),
                (10.40, 108.83, 5.55),
                (10.13, 106.06, 7.50),
                (9.98, 102.31, 9.45),
                (9.89, 97.50, 11.4),
                (9.81, 90.94, 0)
])
datasets.append([
                (13, 180, 40),
                (12.23, 161.25, 38.05),
                (11.49, 143.11, 37),
                (10.85, 125.60, 35.50),
                (10.38, 108.72, 34),
                (10.11, 92.49, 5.50),
                (10.08, 89.80, 0)
])
datasets.append([
                (13, 270, 40),
                (12.75, 251.26, 39),
                (12.28, 232.91, 38),
                (11.62, 214.09, 37),
                (10.85, 197.47, 36),
                (10.03, 180.38, 35),
                (9.23, 163.71, 34),
                (8.53, 147.48, 33),
                (7.96, 131.67, 32),
                (7.58, 116.31, 31),
                (7.41, 101.38, 30),
                (7.71, 86.91, 29),
                (8.22, 72.88, 28),
                (8.71, 59.29, 0),
                (9.09, 59.29, -15),
                (9.37, 66.74, -13),
                (9.58, 73.19, -10),
                (9.71, 78.18, -8),
                (9.81, 81.92, -5.50),
                (9.92, 85.50, -3.50),
                (9.97, 89.23, 0)
])
datasets.append([
                (19, 90, -18),
                (18.85, 98.88, -16),
                (18.57, 106.81, -14),
                (18.18, 113.76, -12),
                (17.69, 119.72, -10),
                (17.13, 124.71, -8),
                (16.51, 128.70, -6),
                (15.84, 131.69, -4),
                (15.16, 133.69, -2),
                (14.45, 134.69, 0),
                (13.75, 134.69, 2),
                (13.06, 133.69, 4),
                (12.40, 131.69, 6),
                (11.78, 128.70, 8),
                (11.22, 124.71, 10),
                (10.74, 119.72, 12),
                (10.35, 113.76, 14),
                (10.7, 106.81, 16),
                (9.93, 98.89, 18),
                (9.89, 90, 0)
])
datasets.append([
                (19, 180, 19),
                (18.05, 170.63, 17.95),
                (17.12, 161.77, 16.90),
                (16.21, 153.41, 15.85),
                (15.35, 145.56, 14.80),
                (14.55, 138.22, 13.75),
                (13.83, 131.40, 12.70),
                (13.18, 125.09, 11.65),
                (12.62, 119.29, 10.60),
                (12.14, 114.01, 9.55),
                (11.74, 109.26, 8.50),
                (11.42, 105.01, 7.45),
                (11.16, 101.30, 6.40),
                (10.96, 98.10, 5.45),
                (10.73, 95.43, 4.50),
                (1053, 93.28, 3.55),
                (1037, 91.66, 2.50),
                (10.11, 90.56, 0)
])
datasets.append([
                (19, 270, 30),
                (18.78, 255.53, 29),
                (18.36, 241.50, 28),
                (17.76, 227.92, 27),
                (17.03, 214.80, 26),
                (16.19, 202.14, 25),
                (15.29, 189.94, 24),
                (14.37, 178.21, 23),
                (13.46, 166.94, 22),
                (12.61, 156.14, 21),
                (11.83, 145.82, 20),
                (11.15, 135.97, 19),
                (10.58, 126.61, 18),
                (10.13, 117.72, 17),
                (9.99, 109.31, 16.2),
                (9.91, 101.39, 15.4),
                (9.85, 93.95, 14.6),
                (9.80, 91.06, 13.8)
  
])

For the step 2 and 3, we need to extract fuzzy rules from the datapoints and then eliminate incompatible rules with reference to their associated degrees.

In [ ]:
# Rule Extraction - Degree Assignment Phase 2 and 3

rules = []
for dataset in datasets:
    for data in dataset:
        for memx_key, memx_value in x.items():
            for memp_key, memp_value in phi.items():
                for memt_key, memt_value in theta.items():
                    m_x = triangle_mem(data[0],memx_value)
                    m_p = triangle_mem(data[1],memp_value)
                    m_t = triangle_mem(data[2],memt_value)
                    deg = m_x * m_p * m_t
                    if deg > 0 :
                        rules.append(((memx_key,memp_key),memt_key,deg))

# Eliminate incompatible rules, or repetitive rules 
while True:
    len_prev = len(rules)
    
    for rule1 in rules:
        for rule2 in rules:
            if rule1[0] == rule2[0] and rule1[1] != rule2[1]:
                if rule1[2] <= rule2[2]:
                    try:
                        rules.remove(rule1)
                    except:
                        pass
                else:
                    try:
                        rules.remove(rule2)
                    except:
                        pass
            if rule1[0] == rule2[0] and rule1[1] == rule2[1] and rule1[2] != rule2[2]:
                if rule1[2] <= rule2[2]:
                    try:
                        rules.remove(rule1)
                    except:
                        pass
                else:
                    try:
                        rules.remove(rule2)
                    except:
                        pass
    if len_prev == len(rules):
        break

For the first question, the extracted rules and their degrees are as follows.

In [ ]:
# Question 1 
rules

As the last step, deffuzification consists of extracting the theta value from rules and a datapoint like (x,\phi). The function below is set to do so.

In [ ]:
# Defuzzification - Phase 4

def defuzz(x_test, phi_test):
    numi = 0
    denumi = 0

    for i in range(len(rules)):
        I_1 = rules[i][0][0]
        I_2 = rules[i][0][1]
        O = rules[i][1]
        # print(I_1, I_2, O)
        m_I_1 = triangle_mem(x_test, x[I_1])
        m_I_2 = triangle_mem(phi_test, phi[I_2])

        m_o = m_I_1 * m_I_2
        # print(m_o)
        theta_bar = theta[O][1]

        numi += m_o * theta_bar
        denumi += m_o
    
    return numi / denumi

defuzz(18,200)

The following then calculates the next datapoint using x, \phi, and \theta.

In [ ]:
# X and Phi extraction 
import math

def X(x,phi,theta):
    return x + math.cos(math.radians(phi)+math.radians(theta)) + math.sin(math.radians(phi)) * math.sin(math.radians(theta))

def PHI(phi,theta):
    return phi - math.degrees(math.asin((2 * math.sin(theta))/4))

At last, we can record each of the points visited for reaching the final position (10,90).

In [ ]:

def track(x_test, phi_test):
    track_ls = []

    x_curr = x_test
    phi_curr = phi_test

    while True:
        theta = defuzz(x_curr, phi_curr)
        track_ls.append((x_curr,phi_curr, theta))
        # print(x_curr, phi_curr, theta)
        if math.fabs(x_curr - 10) < 2 and  math.fabs(phi_curr - 90) < 8:
            break
        x_curr = X(x_curr,phi_curr,theta)
        phi_curr = PHI(phi_curr, theta)
    
    return track_ls


Then we can test the fuzzy system using some test datapoints.

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.lines as lines
from PIL import Image, ImageDraw
import PIL
from pylab import *

track_list_1 = track(5,120)
points = []
i = 10
for x_t,phi_t,_ in track_list_1:
    x1 = x_t * 10
    y1 = i 
    x1_n = x1 + 30 * math.cos(math.radians(phi_t)) 
    y1_n = i + 30 * math.sin(math.radians(phi_t)) 
    points.append(((x1,y1),(x1_n,y1_n)))
    i+=10


w, h = 280,280


img = Image.new('RGB',(w,h),(255,255,255))
draw = ImageDraw.Draw(img)

for point in points:    

    draw.line((point[1][0],point[1][1],point[0][0],point[0][1]),fill=(0,0,0), width=1)

imshow(img.transpose(method= PIL.Image.FLIP_TOP_BOTTOM))

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.lines as lines
from PIL import Image, ImageDraw
import PIL
from pylab import *

track_list_1 = track(9,20)
points = []
i = 5
for x_t,phi_t,_ in track_list_1:
    x1 = x_t * 5
    y1 = i 
    x1_n = x1 + 30 * math.cos(math.radians(phi_t)) 
    y1_n = i + 30 * math.sin(math.radians(phi_t)) 
    points.append(((x1,y1),(x1_n,y1_n)))
    i+=10


w, h = 280,280


img = Image.new('RGB',(w,h),(255,255,255))
draw = ImageDraw.Draw(img)

for point in points:    

    draw.line((point[1][0],point[1][1],point[0][0],point[0][1]),fill=(0,0,0), width=1)

imshow(img.transpose(method= PIL.Image.FLIP_TOP_BOTTOM))

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.lines as lines
from PIL import Image, ImageDraw
import PIL
from pylab import *

track_list_1 = track(15,70)
points = []
i = 5
for x_t,phi_t,_ in track_list_1:
    x1 = x_t * 5
    y1 = i 
    x1_n = x1 + 30 * math.cos(math.radians(phi_t)) 
    y1_n = i + 30 * math.sin(math.radians(phi_t)) 
    points.append(((x1,y1),(x1_n,y1_n)))
    i+=10


w, h = 250,250


img = Image.new('RGB',(w,h),(255,255,255))
draw = ImageDraw.Draw(img)

for point in points:    

    draw.line((point[1][0],point[1][1],point[0][0],point[0][1]),fill=(0,0,0), width=1)

imshow(img.transpose(method= PIL.Image.FLIP_TOP_BOTTOM))

For question 3, we re-run the rule extraction module using only the first three datapoints for each of the tables.

In [ ]:
# Question 3

rule_3 = []
for dataset in datasets:
    for data in dataset[:3]:
        for memx_key, memx_value in x.items():
            for memp_key, memp_value in phi.items():
                for memt_key, memt_value in theta.items():
                    m_x = triangle_mem(data[0],memx_value)
                    m_p = triangle_mem(data[1],memp_value)
                    m_t = triangle_mem(data[2],memt_value)
                    deg = m_x * m_p * m_t
                    if deg > 0 :
                        rule_3.append(((memx_key,memp_key),memt_key,deg))

while True:
    len_prev = len(rule_3)
    
    for rule1 in rule_3:
        for rule2 in rule_3:
            if rule1[0] == rule2[0] and rule1[1] != rule2[1]:
                if rule1[2] <= rule2[2]:
                    try:
                        rule_3.remove(rule1)
                    except:
                        pass
                else:
                    try:
                        rule_3.remove(rule2)
                    except:
                        pass
            if rule1[0] == rule2[0] and rule1[1] == rule2[1] and rule1[2] != rule2[2]:
                if rule1[2] <= rule2[2]:
                    try:
                        rule_3.remove(rule1)
                    except:
                        pass
                else:
                    try:
                        rule_3.remove(rule2)
                    except:
                        pass
    if len_prev == len(rule_3):
        break

In [ ]:
rule_3

In [ ]:
rules

In [ ]:
# Defuzzification - Phase 4

def defuzz_3(x_test, phi_test):
    numi = 0
    denumi = 0

    for i in range(len(rule_3)):
        I_1 = rule_3[i][0][0]
        I_2 = rule_3[i][0][1]
        O = rule_3[i][1]
        # print(I_1, I_2, O)
        m_I_1 = triangle_mem(x_test, x[I_1])
        m_I_2 = triangle_mem(phi_test, phi[I_2])

        m_o = m_I_1 * m_I_2
        # print(m_o)
        theta_bar = theta[O][1]

        numi += m_o * theta_bar
        denumi += m_o
    
    return numi / denumi

In [ ]:
def track_3(x_test, phi_test):
    track_ls = []

    x_curr = x_test
    phi_curr = phi_test

    while True:
        theta = defuzz_3(x_curr, phi_curr)
        track_ls.append((x_curr,phi_curr, theta))
        # print(x_curr, phi_curr, theta)
        if math.fabs(x_curr - 10) < 2 and  math.fabs(phi_curr - 90) < 12:
            break
        x_curr = X(x_curr,phi_curr,theta)
        phi_curr = PHI(phi_curr, theta)
    
    return track_ls

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.lines as lines
from PIL import Image, ImageDraw
import PIL
from pylab import *

track_list_1 = track_3(5,120)
points = []
i = 10
for x_t,phi_t,_ in track_list_1:
    x1 = x_t * 10
    y1 = i 
    x1_n = x1 + 50 * math.cos(math.radians(phi_t)) 
    y1_n = i + 50 * math.sin(math.radians(phi_t)) 
    points.append(((x1,y1),(x1_n,y1_n)))
    i+=10


w, h = 300,300


img = Image.new('RGB',(w,h),(255,255,255))
draw = ImageDraw.Draw(img)

for point in points:    

    draw.line((point[1][0],point[1][1],point[0][0],point[0][1]),fill=(0,0,0), width=1)

imshow(img.transpose(method= PIL.Image.FLIP_TOP_BOTTOM))

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.lines as lines
from PIL import Image, ImageDraw
import PIL
from pylab import *

track_list_1 = track_3(9,20)
points = []
i = 5
for x_t,phi_t,_ in track_list_1:
    x1 = x_t * 5
    y1 = i 
    x1_n = x1 + 30 * math.cos(math.radians(phi_t)) 
    y1_n = i + 30 * math.sin(math.radians(phi_t)) 
    points.append(((x1,y1),(x1_n,y1_n)))
    i+=10


w, h = 250,250


img = Image.new('RGB',(w,h),(255,255,255))
draw = ImageDraw.Draw(img)

for point in points:    

    draw.line((point[1][0],point[1][1],point[0][0],point[0][1]),fill=(0,0,0), width=1)

imshow(img.transpose(method= PIL.Image.FLIP_TOP_BOTTOM))

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.lines as lines
from PIL import Image, ImageDraw
import PIL
from pylab import *

track_list_1 = track_3(15,70)
points = []
i = 5
for x_t,phi_t,_ in track_list_1:
    x1 = x_t * 5
    y1 = i 
    x1_n = x1 + 30 * math.cos(math.radians(phi_t)) 
    y1_n = i + 30 * math.sin(math.radians(phi_t)) 
    points.append(((x1,y1),(x1_n,y1_n)))
    i+=10


w, h = 200,200


img = Image.new('RGB',(w,h),(255,255,255))
draw = ImageDraw.Draw(img)

for point in points:    

    draw.line((point[1][0],point[1][1],point[0][0],point[0][1]),fill=(0,0,0), width=1)

imshow(img.transpose(method= PIL.Image.FLIP_TOP_BOTTOM))

In [ ]:
rule_3.append( (('CE', 'B2'), 'B2', 1))

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.lines as lines
from PIL import Image, ImageDraw
import PIL
from pylab import *

track_list_1 = track_3(15,70)
points = []
i = 5
for x_t,phi_t,_ in track_list_1:
    x1 = x_t * 5
    y1 = i 
    x1_n = x1 + 30 * math.cos(math.radians(phi_t)) 
    y1_n = i + 30 * math.sin(math.radians(phi_t)) 
    points.append(((x1,y1),(x1_n,y1_n)))
    i+=10


w, h = 200,200


img = Image.new('RGB',(w,h),(255,255,255))
draw = ImageDraw.Draw(img)

for point in points:    

    draw.line((point[1][0],point[1][1],point[0][0],point[0][1]),fill=(0,0,0), width=1)

imshow(img.transpose(method= PIL.Image.FLIP_TOP_BOTTOM))

As we can see in the last 4, This is not logical and not possible. the first 3 were much more logical.